# Generated by Django 4.1.2 on 2022-11-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
